"""add tenant detail fields

Revision ID: b1eccf4536e1
Revises: 80c8bdccdf1b
Create Date: 2025-09-07 12:14:06.895111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eccf4536e1'
down_revision: Union[str, Sequence[str], None] = '80c8bdccdf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('id_type', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('id_number', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('move_in_date', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'metadata')
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'move_in_date')
    op.drop_column('tenants', 'emergency_contact_phone')
    op.drop_column('tenants', 'emergency_contact_name')
    op.drop_column('tenants', 'photo')
    op.drop_column('tenants', 'id_number')
    op.drop_column('tenants', 'id_type')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'postal_code')
    op.drop_column('tenants', 'state')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'street')
    op.drop_column('tenants', 'gender')
    op.drop_column('tenants', 'dob')
    # ### end Alembic commands ###
