"""add room detail fields

Revision ID: d1e8b3eb23f8
Revises: 2ab95666f0e6
Create Date: 2025-08-30 17:15:04.204925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e8b3eb23f8'
down_revision: Union[str, Sequence[str], None] = '2ab95666f0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('bed_count', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('max_occupancy', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('sq_meters', sa.Float(), nullable=True))
    op.add_column('rooms', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('rooms', sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('rooms', sa.Column('has_ac', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('private_bath', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('accessible', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'available')
    op.drop_column('rooms', 'images')
    op.drop_column('rooms', 'tags')
    op.drop_column('rooms', 'amenities')
    op.drop_column('rooms', 'accessible')
    op.drop_column('rooms', 'private_bath')
    op.drop_column('rooms', 'has_ac')
    op.drop_column('rooms', 'deposit_amount')
    op.drop_column('rooms', 'price')
    op.drop_column('rooms', 'sq_meters')
    op.drop_column('rooms', 'max_occupancy')
    op.drop_column('rooms', 'bed_count')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'title')
    # ### end Alembic commands ###
